# Generated by Django 5.2.3 on 2025-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_backup_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='password_hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
