# Generated by Django 5.2.3 on 2025-06-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('wallet', '0004_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='encrypted_mnemonic',
            field=models.TextField(default='PLACEHOLDER_ENCRYPTED_MNEMONIC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='users.googleuser'),
        ),
    ]
