# Generated by Django 5.2.3 on 2025-06-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_googleuser_created_at_googleuser_last_login'),
        ('wallet', '0005_wallet_encrypted_mnemonic_alter_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.googleuser'),
        ),
    ]
