# Generated by Django 5.2.3 on 2025-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='encryption_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
