# Generated by Django 5.2.3 on 2025-06-24 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_googleuser_email'),
        ('wallet', '0007_wallet_encryption_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='users.googleuser'),
        ),
    ]
