# Generated by Django 5.2.3 on 2025-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
