# Generated by Django 5.2.3 on 2025-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_googleuser_created_at_googleuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
